ENG-3667: Changed the endpoint to extract plugins from component-manager
entando/entando-bundler pull request #81
Opened 2022-05-06 14:48 UTC by ffleandro

- Changed the endpoint to extract plugins from component-manager instead of k8s-service;
- Added plugin environment variables extraction;
 - Added a warning when extracting a plugin that has external config/secret maps;

2022-05-06 14:49 UTC, firegloves approved these changes
LGTM

2022-05-06 17:47 UTC, w-caffiero-entando requested changes

2022-05-06 17:47 UTC, w-caffiero-entando commented on lib/env-bundler.js
> +      console.warn('WARNING: Extracted plugin has an external secret of config map that needs to be manually exported: ', c.name, v.name);
@ffleandro please change to:

> WARNING: Extracted plugin's variable "..." references k8s secret or configmap "...", that will not be extracted.

2022-05-09 07:53 UTC, firegloves commented
@ffleandro we forgot to update the plugin descriptor version to `v4`

2022-05-12 15:29 UTC, w-caffiero-entando approved these changes

2022-05-13 08:57 UTC, merged